# Generated by Django 6.0.4 on 2026-04-20 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_emaillog_synchistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidature',
            options={'ordering': ['-score', '-updated_at']},
        ),
        migrations.AddField(
            model_name='candidat',
            name='annees_experience',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='candidat',
            name='competences',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='consentement_rgpd',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='current_title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='candidat',
            name='langues',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='localisation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidat',
            name='niveau_etudes',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidat',
            name='resume_profil',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='soft_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='source',
            field=models.CharField(default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='candidat',
            name='source_detail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidature',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_candidatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidature',
            name='decision_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='explication_score',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='recommandation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidature',
            name='score_details_json',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='source_channel',
            field=models.CharField(default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='candidature',
            name='workflow_step',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='poste',
            name='competences_optionnelles',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poste',
            name='departement',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='poste',
            name='experience_min_annees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poste',
            name='langues_requises',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='poste',
            name='localisation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='poste',
            name='niveau_etudes_requis',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='poste',
            name='niveau_priorite',
            field=models.CharField(default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='poste',
            name='poids_competences',
            field=models.FloatField(default=35),
        ),
        migrations.AddField(
            model_name='poste',
            name='poids_experience',
            field=models.FloatField(default=25),
        ),
        migrations.AddField(
            model_name='poste',
            name='poids_formation',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='poste',
            name='poids_langues',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='poste',
            name='poids_localisation',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='poste',
            name='poids_soft_skills',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='poste',
            name='quota_cible',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='poste',
            name='score_qualification',
            field=models.FloatField(default=70),
        ),
        migrations.AddField(
            model_name='poste',
            name='type_contrat',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='poste',
            name='workflow_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('prequalifie', 'Pre-qualifie'), ('shortlist', 'Shortlist'), ('entretien', 'Entretien'), ('finaliste', 'Finaliste'), ('offre', 'Offre'), ('en_cours', 'En cours'), ('accepte', 'Accepte'), ('refuse', 'Refuse'), ('archive', 'Archive')], default='nouveau', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('rh', 'Responsable RH'), ('recruteur', 'Recruteur'), ('manager', 'Manager')], default='recruteur', max_length=20),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('processed', 'Traite avec succes'), ('duplicate', 'Doublon ignore'), ('error', 'Erreur de traitement'), ('no_cv', 'Pas de CV detecte')], default='processed', max_length=20),
        ),
    ]
