# Generated by Django 6.0.4 on 2026-05-04 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_domain_and_status_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('type_entretien', models.CharField(choices=[('rh', 'Entretien RH'), ('technique', 'Entretien technique'), ('final', 'Entretien final'), ('autre', 'Autre')], default='rh', max_length=20)),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='recruitment.candidature')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens_planifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interviews',
                'ordering': ['debut'],
            },
        ),
    ]
