# Generated by Django 6.0.4 on 2026-05-04 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_entretien_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant')], max_length=20)),
                ('text', models.TextField()),
                ('highlights_json', models.TextField(blank=True, default='[]')),
                ('suggested_actions_json', models.TextField(blank=True, default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='chat_messag_user_id_ecc172_idx')],
            },
        ),
    ]
