# Generated by Django 6.0.4 on 2026-05-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_chat_conversation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_messag_convers_0a903c_idx',
            old_name='chat_messag_conversa_idx',
        ),
        migrations.AddIndex(
            model_name='candidat',
            index=models.Index(fields=['created_by', 'created_at'], name='candidates_created_b4b7a8_idx'),
        ),
        migrations.AddIndex(
            model_name='candidat',
            index=models.Index(fields=['created_at'], name='candidates_created_893b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='candidat',
            index=models.Index(fields=['nom', 'prenom'], name='candidates_nom_7289cf_idx'),
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['created_by', 'statut'], name='application_created_860681_idx'),
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['poste', 'statut'], name='application_poste_i_aa723b_idx'),
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['candidat', 'statut'], name='application_candida_2a1173_idx'),
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['score'], name='application_score_d2b93b_idx'),
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['statut', 'updated_at'], name='application_statut_b65d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='poste',
            index=models.Index(fields=['created_by', 'workflow_actif'], name='job_positio_created_f8f7de_idx'),
        ),
        migrations.AddIndex(
            model_name='poste',
            index=models.Index(fields=['created_at'], name='job_positio_created_28b04a_idx'),
        ),
    ]
